[package]
name = "core"
version = "0.1.0"
authors = []

[dependencies]
util = { path = "../util" }
chain = { path = "../chain" }
bigint = {path = "../util/bigint"}
crypto = {path = "../crypto"}
bincode = "0.8.0"
log = "0.3"
time = "0.1"
parking_lot = "0.4"