[package]
name = "util"
version = "0.1.0"
authors = []

[dependencies]
sha3 = { path = "./sha3"}
serde = "1.0"
serde_derive = "1.0"
bincode = "0.8.0"
rustc-serialize = "0.3"
parking_lot = "0.4"
rand = "0.3"
serde_json = "1.0"