[package]
name = "util"
version = "0.1.0"
authors = []

[dependencies]
sha3 = { path = "./sha3"}
bigint = { path = "./bigint"}
serde = "1.0"
serde_derive = "1.0"
rustc-serialize = "0.3"
serde_json = "1.0"
tiny-keccak= "1.0"