[package]
name = "util"
version = "0.1.0"
authors = []

[dependencies]
toml = "0.4"
sha3 = { path = "./sha3"}
bigint = { path = "./bigint"}
serde = "1.0"
time = "0.1"
serde_derive = "1.0"
rustc-serialize = "0.3"
rand = "0.3"
serde_json = "1.0"
tiny-keccak= "1.0"