[package]
description = "Rust bindings for tinykeccak C library"
homepage = "http://parity.io"
name = "sha3"
version = "0.1.0"
build = "build.rs"

[dependencies]
tiny-keccak= "1.0"
rand = "0.3"
rustc-serialize = "0.3"
bigint = "2.0"
libc = "0.2.20"
heapsize = "0.4"

[build-dependencies]
gcc = "0.3"