[package]
name = "chain"
version = "0.1.0"
authors = []

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "0.8.0"
parking_lot = "0.4"
rand = "0.3"
serde_json = "1.0"
log = "0.3"
util = { path = "../util" }
crypto = {path = "../crypto"}