[package]
name = "crypto"
version = "0.6.0"
authors = []

[dependencies]
eth-secp256k1 = { git = "https://github.com/bichengming2020/rust-secp256k1" }
lazy_static = "0.2"
rustc-serialize = "0.3"
util = {path = "../util"}
sha3 = {path = "../util/sha3"}
rand = "0.3"
serde = "1.0"
serde_json = "1.0"
